### ISSUE TITLE
Picking of edge handles in Edge Edit mode is broken if one of the edge ends is behind the camera

### ISSUE THREAD

**Issue by distractedmosfet** [blackears/cyclopsLevelBuilder#204]
Initial confession: I have not tested this on the most recent versions so perhaps this is no longer true but the related code appears to still be there so I assume it is. If my assumption is wrong then my apologies for the false alarm.

The issue seems to be the use of Camera3D.unproject_position inside of pick_closest_handle in tool_edit_edge.gd. Apparently this function uses the camera transform to project points from 3d space into camera space and that has a limitation that the documentation hints at but does not outright state: if the position is behind the camera then the transformation is wrong, reduz seems to be saying something to that effect [here](https://github.com/godotengine/godot/issues/1725#issuecomment-97277708).

Currently you project the edge ends onto the screen, then do some math to determine the distance between the click position and that 2d segment. An alternative approach is to take the point_on_seg in 3d space that you already calculate, project that onto the screen and use that to test distance to the click position. Obviously that projection can also be incorrect, but you already check if that point is behind the camera and discard it later so that should catch that. This modification seems to work for me.

**Comment by blackears** [comment]
The pick distance is being done in screen space so that the radius of the pick vertex is the same regardless of how far away from the camera it is.

I've added a frustum check to the vertex, edge and face tools to make sure you're not picking something behind the camera.  I'm not sure how I could test it though.

If you check out the head, I'm in the middle of changing how UVs are handled, so some UV related functions may not be working properly for now.

**Comment by blackears** [comment]
Thanks for catching that.  I've made a patch to the edge edit tool in the main branch.
